api:
  dashboard: true
  # insecure: true

entryPoints:
  web:
    address: ":80"
  people:
    address: ":3001"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web

log:
  level: DEBUG
